version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  app:
    image: golang:latest
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/go/webgo
    links:
      - db
